= Learning Geb with *The Internet* (ver. 0.58.0 - 10, February 2020)

Examples of https://gebish.org/[Geb] test automation of various popular use cases available, well… on the
Internet :)

A list of such use cases has been collected by https://github.com/tourdedave[Dave Heaffner],
and it's available on https://github.com/tourdedave/the-internet

== Available examples from https://github.com/tourdedave/the-internet[The Internet]

* Done! http://the-internet.herokuapp.com/abtest[A/B Testing]
* Done! http://the-internet.herokuapp.com/add_remove_elements/[Add/Remove Elements]
* Done! http://the-internet.herokuapp.com/basic_auth[Basic Auth] (user and pass: admin)
* Done! http://the-internet.herokuapp.com/broken_images[Broken Images]
* Done! http://the-internet.herokuapp.com/challenging_dom[Challenging DOM]
* Done! http://the-internet.herokuapp.com/checkboxes[Checkboxes]
* http://the-internet.herokuapp.com/context_menu[Context Menu]
* http://the-internet.herokuapp.com/digest_auth[Digest Authentication] (user and pass: admin)
* http://the-internet.herokuapp.com/disappearing_elements[Disappearing Elements]
* Done? http://the-internet.herokuapp.com/drag_and_drop[Drag and Drop] - problem…
* http://the-internet.herokuapp.com/dropdown[Dropdown]
* http://the-internet.herokuapp.com/dynamic_content[Dynamic Content]
* http://the-internet.herokuapp.com/dynamic_controls[Dynamic Controls]
* http://the-internet.herokuapp.com/dynamic_loading[Dynamic Loading]
* http://the-internet.herokuapp.com/entry_ad[Entry Ad]
* http://the-internet.herokuapp.com/exit_intent[Exit Intent]
* http://the-internet.herokuapp.com/download[File Download]
* http://the-internet.herokuapp.com/upload[File Upload]
* http://the-internet.herokuapp.com/floating_menu[Floating Menu]
* http://the-internet.herokuapp.com/forgot_password[Forgot Password]
* http://the-internet.herokuapp.com/login[Form Authentication]
* http://the-internet.herokuapp.com/frames[Frames]
* http://the-internet.herokuapp.com/geolocation[Geolocation]
* http://the-internet.herokuapp.com/horizontal_slider[Horizontal Slider]
* http://the-internet.herokuapp.com/hovers[Hovers]
* http://the-internet.herokuapp.com/infinite_scroll[Infinite Scroll]
* W-I-P http://the-internet.herokuapp.com/inputs[Inputs]
* http://the-internet.herokuapp.com/jqueryui/menu[JQuery UI Menus]
* http://the-internet.herokuapp.com/javascript_alerts[JavaScript Alerts]
* http://the-internet.herokuapp.com/javascript_error[JavaScript onload event error]
* http://the-internet.herokuapp.com/key_presses[Key Presses]
* Done! http://the-internet.herokuapp.com/large[Large &amp; Deep DOM]
* Done! http://the-internet.herokuapp.com/windows[Multiple Windows]
* http://the-internet.herokuapp.com/nested_frames[Nested Frames]
* http://the-internet.herokuapp.com/notification_message[Notification Messages]
* Done! http://the-internet.herokuapp.com/redirector[Redirect Link]
* http://the-internet.herokuapp.com/download_secure[Secure File Download]
* http://the-internet.herokuapp.com/shadowdom[Shadow DOM]
* http://the-internet.herokuapp.com/shifting_content[Shifting Content]
* http://the-internet.herokuapp.com/slow[Slow Resources]
* http://the-internet.herokuapp.com/tables[Sortable Data Tables]
* http://the-internet.herokuapp.com/status_codes[Status Codes]
* Done! http://the-internet.herokuapp.com/typos[Typos]
* http://the-internet.herokuapp.com/tinymce[WYSIWYG Editor]

=== Alternatively: run *The Internet* examples locally

* Install https://rvm.io/[rvm]
* Install ruby 2.4.1
[source,bash]
----
rvm install ruby-2.4.1
----

* Install bundler
[source,bash]
----
gem install bundler
----

* Checkout `https://github.com/tourdedave/the-internet`
* Install dependencies
[source,bash]
----
bundle install
----

* Start the server:
[source,bash]
----
rackup
----

* Pages will be available locally:
[source,text]
----
http://localhost:9292/url_path
----

== Notes, how-tos etc.

=== Gradle

See more at: https://guides.gradle.org/building-groovy-libraries

=== Init Gradle project

----
gradle init --type groovy-library

----

=== Passing a configuration from Gradle to JVM

Inspired
by https://stackoverflow.com/questions/28985395/gradle-gebconfig-groovy-parameterized

In `build.gradle` pass the gradle project property to system property:

[source,groovy]
----
tasks.withType(Test) {
    systemProperty 'org.askucins.webdriver', project.findProperty('webdriver')
    // [...]
}
----

Then in the `GebConfig.groovy` select your webdriver based on the passed system property:

[source,groovy]
----
import org.openqa.selenium.firefox.FirefoxDriver

import static org.askucins.utils.WebDriverConfiguration.chromeDriver

switch (System.getProperty('org.askucins.webdriver')) {
    case 'firefox':
        driver = { new FirefoxDriver() }
        break
    case 'chrome':
        driver = { chromeDriver([headless: false]) }
        break
    default:
        driver = { chromeDriver([headless: true]) }
}
----

Also, if you want to e.g. run execute tests with firefox you may run this:

[source,bash]
----
gw test -Pwebdriver=firefox
----

==== Update 2020-02-23

Although that works just fine, one can use rather the built-in concept of GebConfig.environments, so then
in `build.gradle` there would be:

[source,groovy]
----
tasks.withType(Test) {
    systemProperty 'geb.env', project.findProperty('webdriver') ?: 'chrome'
    // [...]
}
----

Aso, then in the `GebConfig.groovy`:

[source,groovy]
----
environments {
    firefox {
        atCheckWaiting = 1
        driver = { new FirefoxDriver() }
    }
    firefoxHeadless {
        atCheckWaiting = 1
        driver = { customizedFirefoxDriver([headless: true]) }
    }
    chrome {
        driver = { customizedChromeDriver([headless: false]) }
    }
    chromeHeadless {
        driver = { customizedChromeDriver([headless: true]) }
    }
}
----

With that setup if the gradle project property 'webdriver' is not defined that 'chrome' environment will be used, while
when it is defined - an appropriate environment will be picked up, e.g.

[source,bash]
----
gw test -Pwebdriver=firefox
----

=== Geb: Finding vs filtering

* A method `$(...)` (or its alias `find(...)`) searches in depth, looking for descendants
* Methods `filter(...)` and `not(...)` search in breadth, limiting the found content.

Also, a quote from https://gebish.org/manual/current/[The Book of Geb]:

____

The `find()` and `$()` _methods_ support the exact same argument types as the $() _function_.
The `filter()`, `not()`, `has()` and `hasNot()` _methods_ have the same signatures -
they accept: a selector string, a predicate map or both.
These methods return a new navigator object that represents the new content.

____

== Questions

. Can webdriver access a JS script from the page source?